# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Andrew Gurung
tagline:          ' A Journey Through Front End Web Development'
description:      '&lt;software-developer&gt; <br>A Journey Through Front End Web Development. Follow <a href="https://twitter.com/andrewgurung" target="_blank">@andrewgurung</a>.'
url:              http://andrewgurung.github.io
baseurl:          /
feedurl:          /atom.xml

author:
  name:           'Andrew Gurung'
  url:            https://twitter.com/andrewgurung

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andrewgurung/
